name: Checking Orphaned Debs

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 2 * * *"

jobs:
  checking-orphaned-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checking new orphaned debs I am interested in
        # I want the highlight by failing the job but I want it continue the
        # next step to upload the artifacts i.e. the db
        continue-on-error: true
        run: |
          pip install poetry
          poetry install
          # will create or update package_history.pkl in the same dir
          poetry run ./crawler-wnpp-orphaned.py

      - name: Upload updated database of orphaned debs found
        uses: actions/upload-artifact@v4
        with:
          name: orphaned-debs
          path: ./package_history.pkl

      - name: Download previous database of orphaned debs
        uses: actions/download-artifact@v4
        with:
          name: orphaned-debs
          search-artifacts: true
        # check the artifacts
        run: ls

